import Foundation
import Testing
@testable import KeydexApp

@Test
func shellSettingsStoreSavesAndLoadsConfig() throws {
  let rootURL = temporarySettingsRoot()
  var config = sampleSettingsData(displayMode: .list)
  config.keychainAccess = false
  config.requestPrompt = true
  config.scanSources[2].enabled = true
  config.tags = [
    CredentialTagRow(
      id: try #require(UUID(uuidString: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")),
      name: "Infra",
      assignments: "hashicorp-vault|infra",
      color: .teal
    )
  ]

  try requireSuccess(ShellSettingsStore(rootURL: rootURL).save(config))
  let manifest = try String(contentsOf: settingsManifestURL(rootURL: rootURL), encoding: .utf8)
  let loaded = ShellSettingsStore(rootURL: rootURL).load(defaults: sampleSettingsData())

  #expect(loaded.issueMessage == nil)
  #expect(loaded.config == config)
  #expect(manifest.contains("scanSourceEnabledByID"))
  #expect(manifest.contains("environment-variables"))
  #expect(manifest.contains("Environment variables") == false)
  #expect(manifest.contains("Enumerate non-secret environment values") == false)
}

@Test
func shellSettingsStoreUsesDefaultsWhenManifestIsMissing() {
  let rootURL = temporarySettingsRoot()
  let defaults = sampleSettingsData(displayMode: .cards)

  let loaded = ShellSettingsStore(rootURL: rootURL).load(defaults: defaults)

  #expect(loaded.issueMessage == nil)
  #expect(loaded.config == defaults)
  #expect(FileManager.default.fileExists(atPath: rootURL.path) == false)
}

@Test
func shellSettingsStoreLoadsLegacyFullConfigManifest() throws {
  let rootURL = temporarySettingsRoot()
  try FileManager.default.createDirectory(at: rootURL, withIntermediateDirectories: true)
  try legacyFullConfigManifest.write(
    to: settingsManifestURL(rootURL: rootURL),
    atomically: true,
    encoding: .utf8
  )

  let loaded = ShellSettingsStore(rootURL: rootURL).load(defaults: sampleSettingsData())
  var expected = sampleSettingsData(displayMode: .list)
  expected.keychainAccess = false
  expected.requestPrompt = true
  expected.keychainReferences = []
  expected.scanSources[0].enabled = false
  expected.scanSources[1].enabled = false
  expected.scanSources[2].enabled = true
  expected.scanSources[3].enabled = false
  expected.scanPaths = []
  expected.tags = []
  expected.ignoredSources = []
  expected.unmanagedSources = []

  #expect(loaded.issueMessage == nil)
  #expect(loaded.config == expected)
}

@Test
func shellSettingsStoreSurfacesUnreadableManifestAsIssue() throws {
  let rootURL = temporarySettingsRoot()
  let defaults = sampleSettingsData(displayMode: .cards)
  try FileManager.default.createDirectory(at: rootURL, withIntermediateDirectories: true)
  try "{".write(
    to: settingsManifestURL(rootURL: rootURL),
    atomically: true,
    encoding: .utf8
  )

  let loaded = ShellSettingsStore(rootURL: rootURL).load(defaults: defaults)

  #expect(loaded.config == defaults)
  #expect(
    loaded.issueMessage
      == "Settings could not be read. Default settings are still available."
  )
}

@Test
func sampleSettingsDataUsesUniqueScanSourcePersistenceIDs() {
  let scanSourceIDs = sampleSettingsData().scanSources.map(\.persistenceID)

  #expect(Set(scanSourceIDs).count == scanSourceIDs.count)
}

private func temporarySettingsRoot() -> URL {
  FileManager.default.temporaryDirectory
    .appendingPathComponent(UUID().uuidString, isDirectory: true)
    .appendingPathComponent("Settings", isDirectory: true)
}

private func settingsManifestURL(rootURL: URL) -> URL {
  rootURL.appendingPathComponent("settings.json", isDirectory: false)
}

private let legacyFullConfigManifest = """
  {
    "displayMode" : "list",
    "ignoredSources" : [],
    "keychainAccess" : false,
    "keychainReferences" : [],
    "requestPrompt" : true,
    "scanPaths" : [],
    "scanSources" : [
      {
        "detail" : "Read metadata from macOS keychain entries generated by apps",
        "enabled" : false,
        "id" : "11111111-1111-1111-1111-111111111111",
        "title" : "Keychain"
      },
      {
        "detail" : "Parse ~/.zshrc and ~/.bashrc for export statements",
        "enabled" : false,
        "id" : "22222222-2222-2222-2222-222222222222",
        "title" : "Shell profiles"
      },
      {
        "detail" : "Enumerate non-secret environment values with credential-like names",
        "enabled" : true,
        "id" : "33333333-3333-3333-3333-333333333333",
        "title" : "Environment variables"
      },
      {
        "detail" : "Inspect service config files in common locations",
        "enabled" : false,
        "id" : "44444444-4444-4444-4444-444444444444",
        "title" : "Config files"
      }
    ],
    "tags" : [],
    "unmanagedSources" : []
  }
  """

private func requireSuccess<T>(
  _ result: Result<T, ShellSettingsStoreError>
) throws -> T {
  switch result {
  case .success(let value):
    return value
  case .failure(let error):
    throw SettingsStoreTestError.unexpectedFailure(error)
  }
}

private enum SettingsStoreTestError: Error {
  case unexpectedFailure(ShellSettingsStoreError)
}
