name: Guard

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  guard:
    name: guard
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Guard
        run: ./scripts/guard.sh
